### PR TITLE
Add stellar evo of sun

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
ignore the earlier commits, just look at the diff

### CODE REVIEW

**Comment by hemisemidemipresent** [comment]
@NUSH-Astro/theory are there any mistakes?

**Review by ThePyProgrammer — COMMENTED** [review]
Hm, it definitely needs a lot of formatting fixes. For instance, leaving text simply as you have may make it very unclear as to what you are trying to say.

**Comment by ThePyProgrammer** [comment]
For now at least, the point is that you need to fix up the earlier parts, and fill in the <insert image> tags.

**Comment by hemisemidemipresent** [comment]
> leaving text simply as you have may make it very unclear as to what you are trying to say.

wdym, like the text formatting, or the temporary image text

**Comment by ThePyProgrammer** [comment]
I meant both, but yeah.

Some of it may not seem clear ig.

**Comment by hemisemidemipresent** [comment]
alright I have added some images

honestly I dont know what to write for stellar formation and main sequence

**Comment by jedlimlx** [comment]
I wrote some stuff on nuclear fusion just now. There's a conflict with one of your assets which you probably should resolve. In my opinion it could also be more detailed but I guess I can add on to it after Prannaya feels that its ready to be merged.

**Comment by hemisemidemipresent** [comment]
I agree that it could be more detailed I was just worried people wouldn't understand or it would be too intimidating

I guess you could add more details as time passes

I'll resolve the asset conflict

**Comment by hemisemidemipresent** [comment]
Also currently the assets have black arrows which is kinda hard to see

**Comment by jedlimlx** [comment]
yeah that is being worked on

**Comment by ThePyProgrammer** [comment]
Alright this should be fine, honestly.

I think can merge now.

**Pull request merged**
