### PR TITLE
added images and polished up stellar evo

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
Yeah this should look more decent than the previous iteration

### CODE REVIEW

**Comment by hemisemidemipresent** [comment]
@NUSH-Astro/theory ping cos yes

**Comment by ThePyProgrammer** [comment]
Wait you can't merge it? For simple fixes like this I think you can just go and edit on the actual repo ngl. Anyways I'll merge, I think it's okay.

**Comment by hemisemidemipresent** [comment]
I can merge it but idk how to deploy it
so mainly just to inform of new changes

**Comment by ThePyProgrammer** [comment]
oh ok
it's pretty easy actually, you just need to run ./deploy.sh and if you don't have git bash then just copy each command in the shell file and paste it there
If you want, we can create a deploy.cmd

**Comment by hemisemidemipresent** [comment]
running `mkdocs build`

```
MkDocs encountered as error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in "C:\Users\...\astro-combined-website\mkdocs.yml", line 48, column 20  
```

**Comment by jedlimlx** [comment]
You might need to
```
pip install mkdocs-material
```

**Comment by hemisemidemipresent** [comment]
hmm still gives me an error,

I did `pip install mkdocs-material-extensions` and got a new error so that's progress

upon running `mkdocs build`

```
ERROR   -  Config value: 'markdown_extensions'. Error: anchor_linenums 

Aborted with 1 Configuration Errors!
```

**Pull request merged**
